server:
  port: 8080  # optional; 8080 is default

mastermind:
  code-length: 4
  min-digit: 0
  max-digit: 7
  attempts: 10
  allow-duplicates: true
  use-random-org: true
  random-org:
    timeout-ms: 1200
    base-url: https://www.random.org/integers/

leaderboard:
  topK: 10